package io.bebi.mykotlincompose

import model.Country

internal val countries = listOf(
    Country("Afghanistan", "AF", "🇦🇫"),
    Country("Aland Islands", "AX", "🇦🇽"),
    Country("Albania", "AL", "🇦🇱"),
    Country("Algeria", "DZ", "🇩🇿"),
    Country("American Samoa", "AS", "🇦🇸"),
    Country("Andorra", "AD", "🇦🇩"),
    Country("Angola", "AO", "🇦🇴"),
    Country("Anguilla", "AI", "🇦🇮"),
    Country("Antarctica", "AQ", "🇦🇶"),
    Country("Antigua and Barbuda", "AG", "🇦🇬"),
    Country("Argentina", "AR", "🇦🇷"),
    Country("Armenia", "AM", "🇦🇲"),
    Country("Aruba", "AW", "🇦🇼"),
    Country("Australia", "AU", "🇦🇺"),
    Country("Austria", "AT", "🇦🇹"),
    Country("Azerbaijan", "AZ", "🇦🇿"),
    Country("Bahamas", "BS", "🇧🇸"),
    Country("Bahrain", "BH", "🇧🇭"),
    Country("Bangladesh", "BD", "🇧🇩"),
    Country("Barbados", "BB", "🇧🇧"),
    Country("Belarus", "BY", "🇧🇾"),
    Country("Belgium", "BE", "🇧🇪"),
    Country("Belize", "BZ", "🇧🇿"),
    Country("Benin", "BJ", "🇧🇯"),
    Country("Bermuda", "BM", "🇧🇲"),
    Country("Bhutan", "BT", "🇧🇹"),
    Country("Bolivia", "BO", "🇧🇴"),
    Country("Bosnia and Herzegovina", "BA", "🇧🇦"),
    Country("Botswana", "BW", "🇧🇼"),
    Country("Bouvet Island", "BV", "🇧🇻"),
    Country("Brazil", "BR", "🇧🇷"),
    Country("British Indian Ocean Territory", "IO", "🇮🇴"),
    Country("Brunei Darussalam", "BN", "🇧🇳"),
    Country("Bulgaria", "BG", "🇧🇬"),
    Country("Burkina Faso", "BF", "🇧🇫"),
    Country("Burundi", "BI", "🇧🇮"),
    Country("Cambodia", "KH", "🇰🇭"),
    Country("Cameroon", "CM", "🇨🇲"),
    Country("Canada", "CA", "🇨🇦"),
    Country("Cape Verde", "CV", "🇨🇻"),
    Country("Cayman Islands", "KY", "🇰🇾"),
    Country("Central African Republic", "CF", "🇨🇫"),
    Country("Chad", "TD", "🇹🇩"),
    Country("Chile", "CL", "🇨🇱"),
    Country("China", "CN", "🇨🇳"),
    Country("Christmas Island", "CX", "🇨🇽"),
    Country("Cocos (Keeling) Islands", "CC", "🇨🇨"),
    Country("Colombia", "CO", "🇨🇴"),
    Country("Comoros", "KM", "🇰🇲"),
    Country("Congo", "CG", "🇨🇬"),
    Country("Congo, The Democratic Republic of the", "CD", "🇨🇩"),
    Country("Cook Islands", "CK", "🇨🇰"),
    Country("Costa Rica", "CR", "🇨🇷"),
    Country("Cote D'Ivoire", "CI", "🇨🇮"),
    Country("Croatia", "HR", "🇭🇷"),
    Country("Cuba", "CU", "🇨🇺"),
    Country("Cyprus", "CY", "🇨🇾")
    )